### ISSUE TITLE
templates: update record detail

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-marc21#20]
@hachreak commented on [Wed Mar 09 2016](https://github.com/inveniosoftware/invenio-records-ui/pull/29)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

---

@hachreak commented on [Wed Mar 09 2016](https://github.com/inveniosoftware/invenio-records-ui/pull/29#issuecomment-194226746)

@tiborsimko 

---

@hachreak commented on [Wed Mar 09 2016](https://github.com/inveniosoftware/invenio-records-ui/pull/29#issuecomment-194278165)

ping @jirikuncar 

---

@jirikuncar commented on [Wed Mar 09 2016](https://github.com/inveniosoftware/invenio-records-ui/pull/29#issuecomment-194310751)

IMHO we should not update this template but instead override it in `invenio-marc21`.

---

@lnielsen commented on [Wed Mar 09 2016](https://github.com/inveniosoftware/invenio-records-ui/pull/29#issuecomment-194318452)

@jirikuncar Fully agree - didn't notice before that the PR was actually on records-ui

**Comment by hachreak** [comment]
@jirikuncar @lnielsen  do you mean that I'll create a `detail.html` inside https://github.com/inveniosoftware/invenio-marc21/tree/master/invenio_marc21/templates/invenio_marc21?

**Comment by jirikuncar** [comment]
@hachreak Yes.
