### ISSUE TITLE
Update the demo data

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/invenio-marc21#3]
Some fields are incorrect (DOI in 9xxx fields).
The metadata should be fixed (cleaned according to HOWTOMARC specifications).

**Comment by switowski** [comment]
Find the demodata (in invenio-records ?, maybe in tests), clean the incorrect fields (use dojson to perform identity test - use code from Sami)

**Comment by SamiHiltunen** [comment]
Test function: https://github.com/inveniosoftware/dojson/pull/76/files#diff-09f983a1db5a7aca6102f2e2a260c88cR24

**Comment by switowski** [comment]
(TODO assign to Leo)

**Comment by hachreak** [comment]
Do you mean run this and compare the result with the original?
```bash
dojson -l marcxml -d marcxml do marc21 do to_marc21 < in.xml > out.xml
```

**Comment by hachreak** [comment]
After analyzing  [authority.xml](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/data/marc21/authority.xml) with that command, I found that:

Fields that are defined in `marc21` but not in `to_marc21`:
- [ ] 148
- [ ] 150
- [ ] 371
- [ ] 372
- [ ] 430
- [ ] 450
- [ ] 643
- [ ] 670
- [ ] 678
- [ ] 680

Fields completely missed:
- [ ] 690
- [ ] 913
- [ ] 914
- [ ] 920
- [ ] 961
- [ ] 970
- [ ] 980
- [ ] FFT

**Comment by egabancho** [comment]
Be careful with the authority records, they use a different set of rules 
https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/marc21/model.py#L17

**Comment by hachreak** [comment]
I tried with:
```
dojson -l marcxml -d marcxml do marc21_authority do to_marc21 < authority.xml > /tmp/output.xml
```
But, actually, remains only these tags in `output.xml`:
- 003
- 005
- 024
- 035
- 270
- 856

**Comment by egabancho** [comment]
This is because you are mixing models, the input you have `marc21_authority` and in the output `to_marc21`, which is meant for bibliographic marc and not for authority.

These two they should go in pairs and I am afraid there is no `to_marc21_authority` for now.

**Comment by hachreak** [comment]
I tried the same analysis on [bibliographic.xml](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records%2Fdata%2Fmarc21%2Fbibliographic.xml) and I found this list of missing fields:
- 269
- 590
- 595
- 690
- 691
- 693
- 694
- 695
- 697
- 859
- 901
- 909
- 916
- 960
- 961
- 962
- 963
- 964
- 970
- 980
- 999
- FFT

WDYT @egabancho

**Comment by SamiHiltunen** [comment]
@hachreak When you find a field that is missing, you can check whether it is part of the specification here: https://www.loc.gov/marc/bibliographic/. All the 9xx fields for example are not part of the specification and can be removed.

**Comment by egabancho** [comment]
@SamiHiltunen is right, in general  `59X`, `69X` and `9XX` are custom/local fields and they should not be considered here.
I don't think any of the fields you listed are standard fields :wink:

**Comment by switowski** [comment]
@egabancho There is a small mention of 9xx here:
https://www.loc.gov/marc/bibliographic/bd9xx.html
should we map some of the 9xx, like:
980 -> 800 (Series Personal Name)
or should we leave them out completely ?

**Comment by egabancho** [comment]
I think we should leave them out completely, we are using them with a totally different meaning

**Comment by switowski** [comment]
:+1:

**Comment by hachreak** [comment]
Ok, I made the clean of `bibliographic.xml`.
Only 2 things:
 - sometimes the order is not respected (but I think we need only wait @SamiHiltunen PR)
 - in the field `773` the `t` subfield disappears. @egabancho any idea why? because it seems to be defined in `marc21` and `to_marc21`.

**Comment by switowski** [comment]
@hachreak It might have to do something with the incomplete field_map from the mappings. I have checked the PR https://github.com/inveniosoftware/dojson/pull/76 from @SamiHiltunen and with the code from his pull request it works fine (he is adding field `t` to `field_map`: https://github.com/inveniosoftware/dojson/pull/76/files#diff-9603caabcde9c9896ee926f6d3a8f915R574 so maybe that's why).

**Comment by hachreak** [comment]
@switowski can we close this issue? or maybe ask to sami to automatically close on merge #76

**Comment by switowski** [comment]
Sure, closing as there is nothing else to be done here.
